# Generated by Django 4.0.3 on 2023-08-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
